[package]
name = "royals_ui_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
royals_core = { path = "../royals_core" }
itertools = "0.10.5"