name: check-code
run-name: Check code for formatting and lint
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: rustup component add rustfmt
      - name: Format
        run: cargo fmt --check
  lint:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Prerequisites
        run: apk add --no-cache musl-dev
      - name: Install
        run: rustup component add clippy
      - name: Lint
        run: cargo clippy
  build_ci:
    needs: [lint, format]
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build cli
        run: |
          cd royals_ui_cli
          cargo build
  build_bevy:
    needs: [lint, format]
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build bevy
        run: |
          cd royals_ui_bevy
          cargo build